language: python
cache: pip
python:
- 3.7.8
- 3.9
env:
  global:
  - PYTHONPATH=.:vendor
install:
- pip install coverage
- pip install coveralls
- cp packaging/setup.py .
- pip install .
- pip install -r tests/requirements.txt
script:
- python -m unittest discover -v tests
after_success:
- coverage run -m unittest discover tests
- coveralls
